[package]
name = "stack"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
crossterm = "0.27.0"
itertools = "0.12.0"
notify = "6.1.1"
rustyline = "13.0.0"
lasso = "0.7.2"
syscalls = "0.6.15"

[dev-dependencies]
test-case = "3"

[[bin]]
name = "stack"
path = "src/main.rs"
