[package]
name = "stack"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.27.0"
itertools = "0.12.0"
notify = "6"
rustyline = "13"
lasso = "0.7.2"
syscalls = "0.6.15"
enum-iterator = "1"

[dev-dependencies]
test-case = "3"

[[bin]]
name = "stack"
path = "src/main.rs"
