[package]
name = "stack-core"
version = "0.1.0"
edition = "2021"

[dependencies]
internment = "0.7.4"
unicode-segmentation.workspace = true
compact_str.workspace = true
yansi = "1"

[dev-dependencies]
test-case.workspace = true
