[package]
name = "stack-std"
version = "0.1.0"
edition = "2021"

[dependencies]
stack-core = { path = "../stack-core" }
unicode-segmentation.workspace = true
compact_str.workspace = true
regex = "1.10.4"
